
package ventasdao.ui.abm;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import ventasdao.controladores.FacturaControlador;
import ventasdao.controladores.FormaPagoControlador;
import ventasdao.controladores.ClienteControlador;
import ventasdao.objetos.Cliente;
import ventasdao.objetos.Factura;
import ventasdao.objetos.FormaPago;
import ventasdao.ui.grilla.GrillaFactura;



public class AbmaFactura extends javax.swing.JInternalFrame {
    
  private FacturaControlador facturacontrolador = new FacturaControlador(); 
  private FormaPagoControlador formapagocontrolador = new FormaPagoControlador();
  private ClienteControlador clientecontrolador = new ClienteControlador() ;
  private GrillaFactura grillafactura;
  private DefaultComboBoxModel modelCombo;
  private SimpleDateFormat simpleDateFormat;
  /* private Factura factura;*/
  
  
  
    public AbmaFactura() throws Exception {
        initComponents();
        
       /* facturacontrolador = new FacturaControlador();
      formapagocontrolador = new FormaPagoControlador();*/
      
        
     /*   try {
            grillafactura = new GrillaFactura((ArrayList<Factura>) facturacontrolador.listar());
            jtfactura.setModel(grillafactura);
        } catch (Exception ex) {
            Logger.getLogger(AbmProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            
            ArrayList<FormaPago> formaPagos = formapagocontrolador.listar();
            
            modelCombo = new DefaultComboBoxModel(formaPagos.toArray());
            jcbforma_pago.setModel(modelCombo);
        } catch (Exception ex) {
            Logger.getLogger(AbmaFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            
            ArrayList<Cliente> clientes = clientecontrolador.listar();
            
            modelCombo = new DefaultComboBoxModel(clientes.toArray());
            jcbforma_pago.setModel(modelCombo);
        } catch (Exception ex) {
            Logger.getLogger(AbmaFactura.class.getName()).log(Level.SEVERE, null, ex);
        }   */
     modelCombo = new DefaultComboBoxModel(clientecontrolador.listar().toArray());   
    jcbcliente.setModel(modelCombo);
    
    modelCombo = new DefaultComboBoxModel(formapagocontrolador.listar().toArray());
    jcbforma_pago.setModel(modelCombo);
    
    grillafactura = new GrillaFactura((ArrayList<Factura>) facturacontrolador.listar());
    jtfactura.setModel(grillafactura);
   /* simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy");*/
    
     
     
     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     private void resetFields(){
    
        jtfid.setText("");
        jtfnumero.setText("");
        jtfobservacion.setText("");
       
    }
    private void refreshTable(){
        try {
            jtfactura.setModel(new GrillaFactura((ArrayList<Factura>) facturacontrolador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmaFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfid = new javax.swing.JTextField();
        jcbcliente = new javax.swing.JComboBox<>();
        jcbforma_pago = new javax.swing.JComboBox<>();
        jtfnumero = new javax.swing.JTextField();
        jtfobservacion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtfactura = new javax.swing.JTable();
        jbRegistrar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jtffecha_creacion = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jLabel1.setText("Id");

        jLabel2.setText("Fecha Creacion");

        jLabel3.setText("Cliente");

        jLabel4.setText("Numero");

        jLabel5.setText("Forma de Pago");

        jLabel6.setText("Observacion");

        jtfid.setEnabled(false);
        jtfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfidActionPerformed(evt);
            }
        });

        jcbcliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbforma_pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtfnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfnumeroKeyTyped(evt);
            }
        });

        jtfobservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfobservacionActionPerformed(evt);
            }
        });
        jtfobservacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfobservacionKeyTyped(evt);
            }
        });

        jtfactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtfactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfacturaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtfactura);

        jbRegistrar.setText("Registrar");
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jcbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(jtfnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jcbforma_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtffecha_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jbRegistrar)
                                .addGap(26, 26, 26)
                                .addComponent(jbModificar)
                                .addGap(32, 32, 32)
                                .addComponent(jbEliminar)))
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(31, 31, 31)
                        .addComponent(jtfobservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 600, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jtffecha_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jcbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbforma_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbRegistrar)
                            .addComponent(jbModificar)
                            .addComponent(jbEliminar))
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfobservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(360, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfidActionPerformed

    private void jtfobservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfobservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfobservacionActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
      
      Factura factura = new Factura ();
      
      factura.setObservacion(jtfobservacion.getText());
      factura.setNumero(Integer.parseInt(jtfnumero.getText()));
     /* factura.setFecha_creacion(jdcfecha_creacion.getDate()); */
     factura.setFecha_creacion(jtffecha_creacion.getText());
      factura.setFormapago_id((FormaPago)jcbforma_pago.getSelectedItem());
      factura.setCliente_id((Cliente)jcbcliente.getSelectedItem());
       try{
       this.resetFields();
       this.refreshTable();    
       facturacontrolador.crear(factura);
       }catch (Exception ex){
      Logger.getLogger(AbmaFactura.class.getName()).log(Level.SEVERE, null, ex);
       }
       this.resetFields();
      this.refreshTable();
        
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jtfacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfacturaMouseClicked
        
        Factura factura = grillafactura.getFacturaFromRow(jtfactura.getSelectedRow());
       
       jtfobservacion.setText(factura.getObservacion());
       jtfid.setText(factura.getId().toString());
       jtfnumero.setText(factura.getNumero().toString());
     /*  jdcfecha_creacion.setDate(factura.getFecha_creacion()); */
     jtffecha_creacion.setText(factura.getFecha_creacion());
     
        
        
    }//GEN-LAST:event_jtfacturaMouseClicked

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        Factura  factura = new Factura();
        factura.setObservacion(jtfobservacion.getText());
        factura.setNumero(Integer.parseInt(jtfnumero.getText()));
        factura.setId(Integer.parseInt(jtfid.getText()));
        /*  factura.setFecha_creacion(jdcfecha_creacion.getDate()); **/
        factura.setFecha_creacion(jtffecha_creacion.getText());
        factura.setCliente_id((Cliente)jcbcliente.getSelectedItem());
        factura.setFormapago_id((FormaPago)jcbforma_pago.getSelectedItem());
        
        
        try {
            this.refreshTable();
            this.resetFields();
            facturacontrolador.eliminar(factura);
        } catch (Exception ex) {
            Logger.getLogger(AbmaFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.refreshTable();
        this.resetFields();
       
  
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        try{
        Factura  factura = new Factura();
        factura.setObservacion(jtfobservacion.getText());
        factura.setNumero(Integer.parseInt(jtfnumero.getText()));
        factura.setId(Integer.parseInt(jtfid.getText()));
        /*  factura.setFecha_creacion(jdcfecha_creacion.getDate()); **/
        factura.setFecha_creacion(jtffecha_creacion.getText());
        factura.setCliente_id((Cliente)jcbcliente.getSelectedItem());
        factura.setFormapago_id((FormaPago)jcbforma_pago.getSelectedItem());
        factura.setId(Integer.parseInt(jtfid.getText()));
        this.refreshTable();
        this.resetFields();
        facturacontrolador.modificar(factura);
        }catch(Exception ex) {
            Logger.getLogger(AbmaFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            jtfactura.setModel( new GrillaFactura( (ArrayList<Factura>) facturacontrolador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmaFactura.class.getName()).log(Level.SEVERE, null, ex);
        } 
            this.resetFields();
            this.refreshTable();
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jtfobservacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfobservacionKeyTyped
       char v = evt.getKeyChar();
        if(Character.isDigit(v)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras");
        }
    }//GEN-LAST:event_jtfobservacionKeyTyped

    private void jtfnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfnumeroKeyTyped
         char v = evt.getKeyChar();
        if(Character.isLetter(v)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jtfnumeroKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JComboBox<String> jcbcliente;
    private javax.swing.JComboBox<String> jcbforma_pago;
    private javax.swing.JTable jtfactura;
    private javax.swing.JTextField jtffecha_creacion;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtfnumero;
    private javax.swing.JTextField jtfobservacion;
    // End of variables declaration//GEN-END:variables
}
