
package ventasdao.ui.abm;

import java.util.ArrayList;
import ventasdao.controladores.TipoClienteControlador;
import ventasdao.objetos.TipoCliente;
import ventasdao.ui.grilla.GrillaTipo_Cliente;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class AbmTipo_Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form AbmTipo_Cliente
     */
     private TipoCliente tipocliente;
    private TipoClienteControlador tipoclienteControlador;
    private GrillaTipo_Cliente grillatipo_cliente;
    
    public AbmTipo_Cliente(){
        initComponents();
        
        tipoclienteControlador= new TipoClienteControlador();
           ArrayList<TipoCliente> tipoClientes = new ArrayList();

        try {
            tipoClientes =  (ArrayList<TipoCliente>) tipoclienteControlador.listar();
        } catch (Exception e) {
            e.printStackTrace ();
        }

        grillatipo_cliente = new GrillaTipo_Cliente(tipoClientes);
        jtlistatipocliente.setModel(grillatipo_cliente);
    }
    
    public void limpiarCampos(){
    
    jtfnombre.setText("");
    jtfdescripcion.setText("");
    
    }
    private void refreshTable(){
        try {
            jtlistatipocliente.setModel(new GrillaTipo_Cliente((ArrayList<TipoCliente>) tipoclienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmTipo_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfdescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtlistatipocliente = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("Id");

        jtfid.setEnabled(false);

        jLabel2.setText("Nombre");

        jtfnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnombreActionPerformed(evt);
            }
        });
        jtfnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfnombreKeyTyped(evt);
            }
        });

        jLabel3.setText("Descripcion");

        jtfdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfdescripcionKeyTyped(evt);
            }
        });

        jtlistatipocliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtlistatipocliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtlistatipoclienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtlistatipocliente);

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(26, 26, 26)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jtfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtlistatipoclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtlistatipoclienteMouseClicked
        TipoCliente tipocliente = grillatipo_cliente.getTipoClienteFromRow(jtlistatipocliente.getSelectedRow());
       
       jtfnombre.setText(tipocliente.getNombre());
       jtfdescripcion.setText(tipocliente.getDescripcion());
       jtfid.setText( tipocliente.getId().toString() );
       
    }//GEN-LAST:event_jtlistatipoclienteMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tipocliente= new TipoCliente();

        tipocliente.setNombre(jtfnombre.getText());
        tipocliente.setDescripcion(jtfdescripcion.getText());

        try {
            tipoclienteControlador.crear(tipocliente);
            limpiarCampos();
            this.refreshTable();
        } catch (Exception ex) {
            Logger.getLogger(AbmTipo_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            jtlistatipocliente.setModel(new GrillaTipo_Cliente((ArrayList<TipoCliente>) tipoclienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmTipo_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
            limpiarCampos();
            this.refreshTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnombreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          try {
            // TODO add your handling code here:
            
            // TODO add your handling code here:
            tipocliente = new TipoCliente();
            
            tipocliente.setNombre(jtfnombre.getText() );
            tipocliente.setDescripcion( jtfdescripcion.getText() );
            tipocliente.setId( Integer.parseInt( jtfid.getText() ) );
            
            tipoclienteControlador.modificar(tipocliente);
            limpiarCampos();
            this.refreshTable();
        } catch (Exception ex) {
            Logger.getLogger(AbmTipo_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
            limpiarCampos();
            this.refreshTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           try {
            // TODO add your handling code here:
            
            // TODO add your handling code here:
            tipocliente = new TipoCliente();
            
            tipocliente.setNombre(jtfnombre.getText() );
            tipocliente.setDescripcion( jtfdescripcion.getText() );
            tipocliente.setId( Integer.parseInt( jtfid.getText() ) );
            
            tipoclienteControlador.eliminar(tipocliente);
            limpiarCampos();
            this.refreshTable();
        } catch (Exception ex) {
            Logger.getLogger(AbmTipo_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
            limpiarCampos();
            this.refreshTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtfnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfnombreKeyTyped
        /*char c  = evt.getKeyChar();
        if((c<'a'|| c>'z') && (c<'A'|| c> 'Z') )evt.consume();*/
        char v = evt.getKeyChar();
        if(Character.isDigit(v)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras");
        }
    }//GEN-LAST:event_jtfnombreKeyTyped

    private void jtfdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescripcionKeyTyped
       /* char c  = evt.getKeyChar();
        if((c<'a'|| c>'z') && (c<'A'|| c> 'Z') )evt.consume();*/
       char v = evt.getKeyChar();
        if(Character.isDigit(v)){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras");
        }
    }//GEN-LAST:event_jtfdescripcionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfdescripcion;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtfnombre;
    private javax.swing.JTable jtlistatipocliente;
    // End of variables declaration//GEN-END:variables
}
